### PR TITLE
Add Japanese translation to the GitHub Copilot workshop

### PR DESCRIPTION
**Pull request by SIkebe**
This PR introduces a Japanese translation for the GitHub Copilot workshop.

There’s one point that needs clarification: For the translated filename, should we use the language code such as `ja`, or the country code like `jp`?
The [CONTRIBUTING.md](https://github.com/microsoft/moaw/blob/main/CONTRIBUTING.md#add-translations) states:

> ## Add translations
> 
> You can localize any workshop in this repository by creating a new folder `translations` in the same directory as the original folder, and naming any translated file `<original_name>.<country_code>.<extension>`.
> For example, the French translation of `workshop.md` would be `translations/workshop.fr.md`.
> 
> You can follow the same rule if you need to localize any asset, for example `assets/image.png` should be localized to `assets/translations/image.fr.png`.

However, I’ve noticed that various documents in this repository suggest using the language code. Could you please confirm which is correct?

### CODE REVIEW

**Comment by SIkebe** [comment]
FYI, I published GitHub Pages so that you can review the translated workshop page.
https://sikebe.github.io/moaw/workshop/github-copilot/translations/workshop.ja.md?step=0

**Comment by sinedied** [comment]
Thank you! Using language code here is fine.
If the original assets (images/code) were not updated, could you update the links to point to the original one instead of duplicating them inside the `/translations/` subfolder?

**Comment by SIkebe** [comment]
> Using language code here is fine.

Then, should I fix the [CONTRIBUTING.md](https://github.com/microsoft/moaw/blob/main/CONTRIBUTING.md#add-translations)?

> If the original assets (images/code) were not updated, could you update the links to point to the original one instead of duplicating them inside the /translations/ subfolder?

When I use relative links, the assets were not displayed and you can't download the assets zip file. So I copied those assets into the `/translations/` subfolder.
http://localhost:4200/workshop/github-copilot/translations/workshop.ja.md?step=0

Which url should we use to show the assets on translated page locally and on GitHub Page?

image

image

**Comment by SIkebe** [comment]
Hi @sinedied 
Do you have any opinions or advice regarding the above issue?

**Comment by sinedied** [comment]
Hi @SIkebe and thank you for your patience.
You're right it seems there's an issue when using `../assets`, I'll open an issue and fix it as soon as possible.
Keep in mind it may take 1-2 weeks as it's a very busy period, again I thank you for your contribution and patience.

**Comment by SIkebe** [comment]
Hi @sinedied , what's the status of the issue?

**Comment by sinedied** [comment]
Thanks for your patience, the fix has been published and you can now reference assets from the parent folder.

**Comment by SIkebe** [comment]
@sinedied Thanks! I've confirmed that issue had been fixed, so I removed the duplicated assets.

**Review by sinedied — APPROVED** [review]

**Pull request merged**
