### PR TITLE
Add: Deploying to Azure Container Apps

### PR DESCRIPTION
**Pull request by duffney**
Requesting to add a workshop from MSBuild for ACA to the MOAW repo. :)

### CODE REVIEW

**Comment by sinedied** [comment]
Sorry for the delay, I was off for the last weeks :)

**Comment by duffney** [comment]
Not a problem there was no rush on my end @sinedied, thank you for merging the PR! :) Have a wonderful week.

**Comment by duffney** [comment]
🤦 I may have forgotten to set the workshop to published? Should I submit another PR for that change? Thanks!

**Comment by sinedied** [comment]
> 🤦 I may have forgotten to set the workshop to published? Should I submit another PR for that change? Thanks!

Yes, otherwise it will be available but unlisted in the Moaw website

**Pull request merged**
